set_property PACKAGE_PIN B4 [get_ports display0[0]]
set_property PACKAGE_PIN A4 [get_ports display0[1]]
set_property PACKAGE_PIN A3 [get_ports display0[2]]
set_property PACKAGE_PIN B1 [get_ports display0[3]]
set_property PACKAGE_PIN A1 [get_ports display0[4]]
set_property PACKAGE_PIN B3 [get_ports display0[5]]
set_property PACKAGE_PIN B2 [get_ports display0[6]]

set_property PACKAGE_PIN D4 [get_ports display1[0]]
set_property PACKAGE_PIN E3 [get_ports display1[1]]
set_property PACKAGE_PIN D3 [get_ports display1[2]]
set_property PACKAGE_PIN F4 [get_ports display1[3]]
set_property PACKAGE_PIN F3 [get_ports display1[4]]
set_property PACKAGE_PIN E2 [get_ports display1[5]]
set_property PACKAGE_PIN D2 [get_ports display1[6]]

set_property PACKAGE_PIN G2 [get_ports display_onoff[0]]
set_property PACKAGE_PIN C2 [get_ports display_onoff[1]]
set_property PACKAGE_PIN C1 [get_ports display_onoff[2]]
set_property PACKAGE_PIN H1 [get_ports display_onoff[3]]
set_property PACKAGE_PIN G1 [get_ports display_onoff[4]]
set_property PACKAGE_PIN F1 [get_ports display_onoff[5]]
set_property PACKAGE_PIN E1 [get_ports display_onoff[6]]
set_property PACKAGE_PIN G6 [get_ports display_onoff[7]]

set_property IOSTANDARD LVCMOS33 [get_ports display0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display0[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display0[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display0[6]]

set_property IOSTANDARD LVCMOS33 [get_ports display1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display1[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display1[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display1[6]]

set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[0]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[1]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[2]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[3]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[4]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[5]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[6]]
set_property IOSTANDARD LVCMOS33 [get_ports display_onoff[7]]